default: &default
  adapter: postgresql
  timeout: 5000

development:
  <<: *default
  database: rails5template_development

test:
  <<: *default
  database: rails5template_test

production:
  <<: *default
  database: rails5template
